site_name: HITSZ CTF Wiki
site_description: HITSZ CTF Wiki
site_author: Del0n1x
site_url: http://10.249.12.98:6719/
repo_name: HITSZ-CTF-Wiki
repo_url: https://github.com/Antel0p3/HITSZ-CTF-Wiki
edit_uri: blob/master/docs/zh/docs/
copyright: Copyright &copy; 2020 - 2021 HITSZ CTF Wiki Team
theme:
  name: material
  language: zh
  palette:
    primary: blue
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo2.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Start:
  - index.md
  - join.md
  - members.md
- Introduction:
  - introduction/history.md
  - introduction/mode.md
  - introduction/content.md
  - introduction/experience.md
  - introduction/cgc.md
  - introduction/resources.md
- Misc:
  - misc/introduction.md
  - 知识总结:
    - static/null.md
  - WriteUp:
    - static/null.md
- Crypto:
  - crypto/introduction.md
  - 知识总结:
    - static/null.md
  - WriteUp:
    - static/null.md
- Web:
  - web/introduction.md
  - 知识总结:
    - web/points/website.md
    - 源码泄露:
      - web/points/源码泄露/源码泄露.md
      - web/points/源码泄露/CTF比赛中信息搜集的一些trick.md
      - web/points/源码泄露/十大常见的Web源码泄漏漏洞及其利用.md
    - Linux:
      - web/points/linux/linux管道符与重定向.md
      - web/points/linux/内联执行.md
      - web/points/linux/LD_PRELOAD函数劫持.md
      - web/points/linux/web常用linux路径.md
      - web/points/linux/linux绕过姿势.md
    - SSTI:
      - web/points/ssti/模板的基础语法.md
      - flask:
        - web/points/ssti/flask/flask_ssti.md
        - web/points/ssti/flask/flask_pin.md
      - web/points/ssti/erb注入.md
      - web/points/ssti/php.md
      - web/points/ssti/暴力payload.md
    - Serialize:
      - PHP:
        - web/points/serialize/PHP/php_serialize.md
        - PHP原生类的应用:
          - web/points/serialize/PHP/PHP原生类的应用/DirectoryIterator.md
          - web/points/serialize/PHP/PHP原生类的应用/else.md
          - web/points/serialize/PHP/PHP原生类的应用/Error_Exception.md
          - web/points/serialize/PHP/PHP原生类的应用/SimpleXMLElement.md
          - web/points/serialize/PHP/PHP原生类的应用/SoapClient.md
        - web/points/serialize/PHP/phar反序列化漏洞.md
        - web/points/serialize/PHP/session反序列化跳板.md
      - Java:
        - web/points/serialize/java/xmldecoder.md
      - Python:
        - web/points/serialize/python/Pickle反序列化.md
    - SQL:
      - SQL_Injection:
        - web/points/sql/SQL_Injection/基本原理.md
        - web/points/sql/SQL_Injection/联合查询.md
        - web/points/sql/SQL_Injection/布尔盲注.md
        - web/points/sql/SQL_Injection/宽字节注入.md
        - web/points/sql/SQL_Injection/order_by_排序注入.md
        - web/points/sql/SQL_Injection/堆叠注入.md
        - web/points/sql/SQL_Injection/二次注入.md
        - web/points/sql/SQL_Injection/报错注入.md
        - web/points/sql/SQL_Injection/无列名注入.md
        - SQL注入绕过姿势:
          - web/points/sql/SQL_Injection/SQL注入绕过姿势/万能密码.md
          - web/points/sql/SQL_Injection/SQL注入绕过姿势/SQL注入绕过姿势.md
      - web/points/sql/little_trick.md
      - web/points/sql/基于约束的sql攻击.md
      - web/points/sql/sqlite.md
      - web/points/sql/NOSQL_注入/nosql注入.md
    - Upload:
      - web/points/upload/文件上传基础.md
      - web/points/upload/文件上传中进阶.md
      - web/points/upload/htaccess.md
      - web/points/upload/木马.md
    - Include:
      - web/points/include/include_normal.md
      - web/points/include/include_pro.md
    - web/points/csrf_ssrf_ssi/CSRF.md
    - SSRF:
      - web/points/csrf_ssrf_ssi/SSRF/ssrf.md
      - web/points/csrf_ssrf_ssi/SSRF/Gopher协议.md
      - web/points/csrf_ssrf_ssi/SSRF/FastCGI.md
      - web/points/csrf_ssrf_ssi/SSRF/举例例题.md
      - web/points/csrf_ssrf_ssi/SSRF/练习.md
    - web/points/csrf_ssrf_ssi/SSI.md
    - XSS CSS CSP:
      - XSS:
        - web/points/XSS_CSS_CSP/xss/XSS.md
        - web/points/XSS_CSS_CSP/xss/CTF中的利用姿势.md
      - web/points/XSS_CSS_CSP/css/CSS注入.md
      - web/points/XSS_CSS_CSP/csp/CSP.md
    - XML:
      - web/points/XML/xxe.md
    - 框架漏洞_函数漏洞:
      - PHP:
        - web/points/框架漏洞_函数漏洞/PHP/htaccess文件.md
        - web/points/框架漏洞_函数漏洞/PHP/Thinkphp5.0远程代码执行漏洞.md
        - web/points/框架漏洞_函数漏洞/PHP/传参格式.md
        - web/points/框架漏洞_函数漏洞/PHP/Thinkphp6.0.0-6.0.1文件名上传漏洞.md
        - web/points/框架漏洞_函数漏洞/PHP/get_header().md
        - web/points/框架漏洞_函数漏洞/PHP/弱类型比较.md
        - web/points/框架漏洞_函数漏洞/PHP/空格与WAF.md
        - web/points/框架漏洞_函数漏洞/PHP/php7_segment_fault临时文件包含.md
        - web/points/框架漏洞_函数漏洞/PHP/escapeshellarg()_escapeshellcmd().md
        - web/points/框架漏洞_函数漏洞/PHP/extract变量覆盖.md
        - web/points/框架漏洞_函数漏洞/PHP/assert断言.md
        - web/points/框架漏洞_函数漏洞/PHP/ereg正则%00截断.md
        - web/points/框架漏洞_函数漏洞/PHP/open_basedir绕过.md
        - web/points/框架漏洞_函数漏洞/PHP/PHP-FPM未授权访问漏洞.md
        - web/points/框架漏洞_函数漏洞/PHP/Thinkphp3.2.md
        - web/points/框架漏洞_函数漏洞/PHP/php字符串解析特性.md
        - web/points/框架漏洞_函数漏洞/PHP/常见命令执行函数.md
      - Java:
        - web/points/框架漏洞_函数漏洞/Java/jboss_getshell.md
      - Python:
        - web/points/框架漏洞_函数漏洞/python2_python3/python3/Redis.md
      - Perl:
        - web/points/框架漏洞_函数漏洞/Perl/管道符.md
        - web/points/框架漏洞_函数漏洞/Perl/PARAM.md
      - JavaScript:
        - Nodejs-原型链污染:
          - web/points/框架漏洞_函数漏洞/JavaScript/Node.js/Nodejs-原型链污染/原理.md
          - web/points/框架漏洞_函数漏洞/JavaScript/Node.js/Nodejs-原型链污染/实战.md
        - web/points/框架漏洞_函数漏洞/JavaScript/Node.js/nodejs沙盒.md
        - web/points/框架漏洞_函数漏洞/JavaScript/Node.js/nodejs_unicode字符损坏.md
    - Scripts:
      - web/points/scripts/RC4加密脚本.md
      - web/points/scripts/md5截断爆破.md
      - web/points/scripts/Flask-Session脚本解密.md
      - web/points/scripts/取反字符.md
      - web/points/scripts/php_seed爆破.md
      - web/points/scripts/Php_session中的条件竞争脚本.md
    - Crypto:
      - web/points/crypto/MD5扩展攻击介绍.md
      - web/points/crypto/CBC_Padding_Oracle攻击.md
      - web/points/crypto/CBC字节翻转攻击.md
    - Function_library:
      - web/points/Function_library/JavaScript.md
      - web/points/Function_library/Go.md
      - web/points/Function_library/PHP.md
      - web/points/Function_library/python.md
  - WriteUp:
    - web/writeups/ciscn_easy_ser/ciscn_easy_ser.md
    - web/writeups/Time_based-Rce/Time_based-Rce.md
    - web/writeups/[GKCTF2021]easycms.md
    - web/writeups/[NCTF2019]phar_matches_everything.md
    - web/writeups/[网鼎杯 2020 半决赛]BabyJS.md
    - web/writeups/HITCON 2019 Buggy_Net.md
    - web/writeups/WMCTF2020checkin2.0.md
- Reverse:
  - reverse/introduction.md
  - 知识总结:
    - pwn/points/symbol-restore/symbol-restore.md
  - WriteUp:
    - static/null.md
- Pwn:
  - pwn/introduction.md
  - pwn/roadmap.md
  - 知识总结:
    - pwn/points/elf-file/elf-file.md
    - pwn/points/pwn-tools/pwn-tools.md
    - pwn/points/binary-protection/binary-protection.md
    - pwn/points/change-libc/change-libc.md
    - pwn/points/symbol-restore/symbol-restore.md
  - WriteUp:
    - pwn/writeups/shellwego-wp/shellwego-wp.md
    - pwn/writeups/BJDCTF2020-girlfriend-wp/BJDCTF2020-girlfriend-wp.md
    - pwn/writeups/GDOUCTF2023-easymath-wp/GDOUCTF2023-easymath-wp.md
    - pwn/writeups/NISACTF2022-shoppwn-wp/NISACTF2022-shoppwn-wp.md
    - pwn/writeups/NISACTF2022-uaf-wp/NISACTF2022-uaf-wp.md
    - pwn/writeups/深育杯2021-find-flag-wp/深育杯2021-find-flag-wp.md
    - pwn/writeups/BKP2016-simplecalc-wp/BKP2016-simplecalc-wp.md
    - pwn/writeups/dcquals16-feedme/dcquals16-feedme.md
    - pwn/writeups/csawquals2017-svc-wp/csawquals2017-svc-wp.md
    - pwn/writeups/HS2019-storytime-wp/HS2019-storytime-wp.md
    - pwn/writeups/Backdoorctf2017-bbpwn-wp/Backdoorctf2017-bbpwn-wp.md
    - pwn/writeups/watevrctf2019-betstar-wp/watevrctf2019-betstar-wp.md
    - pwn/writeups/Hacklu2015-stackstuff-wp/Hacklu2015-stackstuff-wp.md
    - pwn/writeups/XCTFQuals2016-b0verfl0w-wp/XCTFQuals2016-b0verfl0w-wp.md
    - pwn/writeups/SwampCTF2019-DreamHeaps-wp/SwampCTF2019-DreamHeaps-wp.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  alternate:
  - link: /
    name: zh - 汉语
  - link: /en/
    name: en - English
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
