site_name: HITSZ CTF Wiki
site_description: HITSZ CTF Wiki
site_author: Del0n1x
site_url: http://10.249.12.98:8021/
repo_name: HITSZ-CTF-Wiki
repo_url: null
edit_uri: blob/master/docs/zh/docs/
copyright: Copyright &copy; 2020 - 2021 HITSZ CTF Wiki Team
theme:
  name: material
  language: zh
  palette:
    primary: Teal
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Start:
  - index.md
  - contribute.md
  - contributer.md
- Introduction:
  - introduction/history.md
  - introduction/mode.md
  - introduction/content.md
  - introduction/experience.md
  - introduction/cgc.md
  - introduction/resources.md
- Misc:
  - misc/introduction.md
  - misc/recon.md
  - 编码分析:
    - misc/encode/communication.md
    - misc/encode/computer.md
    - misc/encode/modern.md
  - misc/prefix.md
  - 图片分析:
    - misc/picture/introduction.md
    - misc/picture/png.md
    - misc/picture/jpg.md
    - misc/picture/gif.md
  - 音频隐写:
    - misc/audio/introduction.md
  - 流量包分析:
    - misc/traffic/introduction.md
    - misc/traffic/fix.md
    - 协议分析:
      - misc/traffic/protocols/readme.md
      - misc/traffic/protocols/wireshark.md
      - misc/traffic/protocols/http.md
      - misc/traffic/protocols/https.md
      - misc/traffic/protocols/ftp.md
      - misc/traffic/protocols/dns.md
      - misc/traffic/protocols/wifi.md
      - misc/traffic/protocols/usb.md
    - misc/traffic/data.md
  - 压缩包分析:
    - misc/archive/zip.md
    - misc/archive/rar.md
  - 磁盘内存分析:
    - misc/disk-memory/introduction.md
    - misc/disk-memory/problem.md
  - Other:
    - misc/other/pyc.md
- Crypto:
  - crypto/introduction.md
  - 基础数学知识:
    - crypto/basic/introduction.md
  - 古典密码:
    - crypto/classical/introduction.md
    - crypto/classical/monoalphabetic.md
    - crypto/classical/polyalphabetic.md
    - crypto/classical/others.md
    - crypto/classical/summary.md
  - 流密码:
    - crypto/streamcipher/intro.md
    - 伪随机数生成器:
      - crypto/streamcipher/prng/intro.md
      - crypto/streamcipher/prng/csprng.md
      - crypto/streamcipher/prng/problem.md
    - 线性同余生成器:
      - crypto/streamcipher/lcg/intro.md
      - crypto/streamcipher/lcg/challenge.md
    - 反馈移位寄存器:
      - crypto/streamcipher/fsr/intro.md
      - crypto/streamcipher/fsr/lfsr.md
      - crypto/streamcipher/fsr/nfsr.md
    - 特殊流密码:
      - crypto/streamcipher/special/rc4.md
  - 块加密:
    - crypto/blockcipher/introduction.md
    - ARX:
      - crypto/blockcipher/arx-operations.md
    - DES:
      - crypto/blockcipher/des.md
    - IDEA:
      - crypto/blockcipher/idea.md
    - AES:
      - crypto/blockcipher/aes.md
    - Simon and Speck:
      - crypto/blockcipher/simon-speck.md
    - 分组模式:
      - crypto/blockcipher/mode/introduction.md
      - crypto/blockcipher/mode/padding.md
      - crypto/blockcipher/mode/ecb.md
      - crypto/blockcipher/mode/cbc.md
      - crypto/blockcipher/mode/pcbc.md
      - crypto/blockcipher/mode/cfb.md
      - crypto/blockcipher/mode/ofb.md
      - crypto/blockcipher/mode/ctr.md
      - crypto/blockcipher/mode/padding-oracle-attack.md
  - 非对称加密:
    - crypto/asymmetric/introduction.md
    - RSA:
      - crypto/asymmetric/rsa/rsa_theory.md
      - crypto/asymmetric/rsa/rsa_module_attack.md
      - crypto/asymmetric/rsa/rsa_e_attack.md
      - crypto/asymmetric/rsa/rsa_d_attack.md
      - crypto/asymmetric/rsa/rsa_coppersmith_attack.md
      - crypto/asymmetric/rsa/rsa_chosen_plain_cipher.md
      - crypto/asymmetric/rsa/rsa_side_channel.md
      - crypto/asymmetric/rsa/rsa_pkcs_attack.md
      - crypto/asymmetric/rsa/rsa_complex.md
    - 离散对数相关:
      - crypto/asymmetric/discrete-log/discrete-log.md
      - crypto/asymmetric/discrete-log/elgamal.md
      - crypto/asymmetric/discrete-log/ecc.md
    - 格密码:
      - crypto/asymmetric/lattice/overview.md
      - crypto/asymmetric/lattice/introduction.md
      - crypto/asymmetric/lattice/lattice-reduction.md
      - crypto/asymmetric/lattice/svp.md
      - crypto/asymmetric/lattice/cvp.md
      - crypto/asymmetric/lattice/knapsack.md
      - crypto/asymmetric/lattice/ntru.md
      - crypto/asymmetric/lattice/lcg.md
  - 哈希函数:
    - crypto/hash/introduction.md
    - MD5:
      - crypto/hash/md5.md
    - SHA1:
      - crypto/hash/sha1.md
    - FNV:
      - crypto/hash/fnv.md
    - Hash Attack:
      - crypto/hash/attack.md
    - crypto/hash/complex.md
  - 数字签名:
    - crypto/signature/introduction.md
    - RSA 数字签名:
      - crypto/signature/rsa.md
    - ElGamal 数字签名:
      - crypto/signature/elgamal.md
    - DSA 数字签名:
      - crypto/signature/dsa.md
  - 攻击思想总结:
    - crypto/attack-summary/attack-mode.md
    - 中间相遇攻击:
      - crypto/attack-summary/meet-in-the-middle.md
    - 比特攻击:
      - crypto/attack-summary/bit-attack.md
  - 证书格式:
    - crypto/certificate/introduction.md
- Web:
  - web/readme.md
  - web/changelog.md
  - web/website.md
  - 源码泄露:
    - web/源码泄露/源码泄露.md
    - web/源码泄露/CTF比赛中信息搜集的一些trick.md
    - web/源码泄露/十大常见的Web源码泄漏漏洞及其利用.md
  - Linux:
    - web/linux/linux管道符与重定向.md
    - web/linux/内联执行.md
    - web/linux/LD_PRELOAD函数劫持.md
    - web/linux/web常用linux路径.md
    - web/linux/linux绕过姿势.md
  - SSTI:
    - web/ssti/模板的基础语法.md
    - flask:
      - web/ssti/flask/flask_ssti.md
      - web/ssti/flask/flask_pin.md
    - web/ssti/erb注入.md
    - web/ssti/php.md
    - web/ssti/暴力payload.md
  - Serialize:
    - PHP:
      - web/serialize/PHP/php_serialize.md
      - PHP原生类的应用:
        - web/serialize/PHP/PHP原生类的应用/DirectoryIterator.md
        - web/serialize/PHP/PHP原生类的应用/else.md
        - web/serialize/PHP/PHP原生类的应用/SimpleXMLElement.md
        - web/serialize/PHP/PHP原生类的应用/SoapClient.md
      - web/serialize/PHP/phar反序列化漏洞.md
      - web/serialize/PHP/session反序列化跳板.md
    - Java:
      - web/serialize/java/xmldecoder.md
    - Python:
      - web/serialize/python/Pickle反序列化.md
  - SQL:
    - SQL_Injection:
      - web/sql/SQL_Injection/基本原理.md
      - web/sql/SQL_Injection/联合查询.md
      - web/sql/SQL_Injection/布尔盲注.md
      - web/sql/SQL_Injection/宽字节注入.md
      - web/sql/SQL_Injection/order_by_排序注入.md
      - web/sql/SQL_Injection/堆叠注入.md
      - web/sql/SQL_Injection/二次注入.md
      - web/sql/SQL_Injection/报错注入.md
      - web/sql/SQL_Injection/无列名注入.md
      - SQL注入绕过姿势:
        - web/sql/SQL_Injection/SQL注入绕过姿势/万能密码.md
        - web/sql/SQL_Injection/SQL注入绕过姿势/SQL注入绕过姿势.md
    - web/sql/little_trick.md
    - web/sql/基于约束的sql攻击.md
    - web/sql/sqlite.md
  - Upload:
    - web/upload/文件上传基础.md
    - web/upload/文件上传中进阶.md
    - web/upload/htaccess.md
  - Include:
    - web/include/include_normal.md
    - web/include/include_pro.md
  - web/csrf_ssrf_ssi/CSRF.md
  - SSRF:
    - web/csrf_ssrf_ssi/SSRF/ssrf.md
    - web/csrf_ssrf_ssi/SSRF/Gopher协议.md
    - web/csrf_ssrf_ssi/SSRF/FastCGI.md
    - web/csrf_ssrf_ssi/SSRF/举例例题.md
    - web/csrf_ssrf_ssi/SSRF/练习.md
  - web/csrf_ssrf_ssi/SSI.md
  - XSS CSS CSP:
    - XSS:
      - web/XSS_CSS_CSP/xss/XSS.md
      - web/XSS_CSS_CSP/xss/CTF中的利用姿势.md
    - web/XSS_CSS_CSP/css/CSS注入.md
    - web/XSS_CSS_CSP/csp/CSP.md
  - 框架漏洞_函数漏洞:
    - PHP:
      - web/框架漏洞_函数漏洞/PHP/htaccess文件.md
      - web/框架漏洞_函数漏洞/PHP/Thinkphp5.0远程代码执行漏洞.md
      - web/框架漏洞_函数漏洞/PHP/传参格式.md
      - web/框架漏洞_函数漏洞/PHP/Thinkphp6.0.0-6.0.1文件名上传漏洞.md
      - web/框架漏洞_函数漏洞/PHP/get_header().md
      - web/框架漏洞_函数漏洞/PHP/弱类型比较.md
      - web/框架漏洞_函数漏洞/PHP/空格与WAF.md
      - web/框架漏洞_函数漏洞/PHP/php7_segment_fault临时文件包含.md
      - web/框架漏洞_函数漏洞/PHP/escapeshellarg()_escapeshellcmd().md
      - web/框架漏洞_函数漏洞/PHP/extract变量覆盖.md
      - web/框架漏洞_函数漏洞/PHP/assert断言.md
      - web/框架漏洞_函数漏洞/PHP/ereg正则%00截断.md
      - web/框架漏洞_函数漏洞/PHP/open_basedir绕过.md
      - web/框架漏洞_函数漏洞/PHP/PHP-FPM未授权访问漏洞.md
    - Perl:
      - web/框架漏洞_函数漏洞/Perl/管道符.md
      - web/框架漏洞_函数漏洞/Perl/PARAM.md
    - JavaScript:
      - Nodejs-原型链污染:
        - web/框架漏洞_函数漏洞/JavaScript/Node.js/Nodejs-原型链污染/原理.md
        - web/框架漏洞_函数漏洞/JavaScript/Node.js/Nodejs-原型链污染/实战.md
      - web/框架漏洞_函数漏洞/JavaScript/Node.js/nodejs沙盒.md
  - Scripts:
    - web/scripts/RC4加密脚本.md
    - web/scripts/md5截断爆破.md
    - web/scripts/Flask-Session脚本解密.md
    - web/scripts/取反字符.md
    - web/scripts/php_seed爆破.md
  - Crypto:
    - web/crypto/MD5扩展攻击介绍.md
    - web/crypto/CBC_Padding_Oracle攻击.md
    - web/crypto/CBC字节翻转攻击.md
  - Function_library:
    - web/Function_library/JavaScript.md
    - web/Function_library/Go.md
    - web/Function_library/PHP.md
    - web/Function_library/python.md
- Assembly:
  - assembly/x86-x64/readme.md
  - assembly/mips/readme.md
  - assembly/arm/readme.md
- Executable:
  - ELF 文件:
    - ELF 文件基本结构:
      - executable/elf/structure/basic-info.md
      - executable/elf/structure/sections.md
      - executable/elf/structure/code-sections.md
      - executable/elf/structure/data-related-sections.md
      - executable/elf/structure/symbol-table.md
      - executable/elf/structure/strings-sections.md
      - executable/elf/structure/dynamic-sections.md
      - executable/elf/structure/misc-sections.md
    - 程序加载:
      - executable/elf/program-loading.md
    - 程序链接:
      - executable/elf/linking/program-linking.md
      - executable/elf/linking/symbol-resolve.md
    - 程序执行流程:
      - executable/elf/running-overview.md
- Reverse:
  - Reverse Overview:
    - reverse/introduction.md
    - reverse/identify-encode-encryption/introduction.md
    - reverse/maze/maze.md
    - reverse/vm/vm.md
    - reverse/unicorn/introduction.md
  - Linux Reverse:
    - reverse/linux/ld_preload.md
    - reverse/linux/false-disasm.md
    - reverse/linux/detect-bp.md
    - reverse/linux/detect-dbg.md
  - Windows Reverse:
    - 脱壳技术:
      - reverse/windows/unpack/packer-introduction.md
      - reverse/windows/unpack/trace.md
      - reverse/windows/unpack/esp.md
      - reverse/windows/unpack/direct-oep.md
      - reverse/windows/unpack/memory.md
      - reverse/windows/unpack/last-exception.md
      - reverse/windows/unpack/sfx.md
      - reverse/windows/unpack/fix-iat.md
      - reverse/windows/unpack/manually-fix-iat.md
      - reverse/windows/unpack/unpack-dll.md
    - 反调试技术:
      - reverse/windows/anti-debug/ntglobalflag.md
      - reverse/windows/anti-debug/heap-flags.md
      - reverse/windows/anti-debug/the-heap.md
      - reverse/windows/anti-debug/int-3.md
      - reverse/windows/anti-debug/isdebuggerpresent.md
      - reverse/windows/anti-debug/checkremotedebuggerpresent.md
      - reverse/windows/anti-debug/ntqueryinformationprocess.md
      - reverse/windows/anti-debug/zwsetinformationthread.md
      - reverse/windows/anti-debug/junk-code.md
      - reverse/windows/anti-debug/example.md
- Pwn:
  - Pwn Overview:
    - pwn/readme.md
  - Linux Pwn:
    - 安全防护机制:
      - pwn/linux/mitigation/canary.md
    - 栈溢出:
      - pwn/linux/stackoverflow/stack-intro.md
      - pwn/linux/stackoverflow/stackoverflow-basic.md
      - pwn/linux/stackoverflow/basic-rop.md
      - pwn/linux/stackoverflow/medium-rop.md
      - 高级 ROP:
        - pwn/linux/stackoverflow/advanced-rop/advanced-rop.md
        - pwn/linux/stackoverflow/advanced-rop/ret2dlresolve.md
        - pwn/linux/stackoverflow/advanced-rop/ret2vdso.md
        - pwn/linux/stackoverflow/advanced-rop/srop.md
      - 花式栈溢出:
        - pwn/linux/stackoverflow/fancy-rop.md
    - 格式化字符串漏洞:
      - pwn/linux/fmtstr/fmtstr_intro.md
      - pwn/linux/fmtstr/fmtstr_exploit.md
      - pwn/linux/fmtstr/fmtstr_example.md
      - pwn/linux/fmtstr/fmtstr_detect.md
    - Glibc Heap 利用:
      - pwn/linux/glibc-heap/introduction.md
      - pwn/linux/glibc-heap/heap_overview.md
      - pwn/linux/glibc-heap/heap_structure.md
      - 深入理解 Ptmalloc2:
        - pwn/linux/glibc-heap/implementation/overview.md
        - pwn/linux/glibc-heap/implementation/basic.md
        - pwn/linux/glibc-heap/implementation/heap-init.md
        - pwn/linux/glibc-heap/implementation/malloc.md
        - pwn/linux/glibc-heap/implementation/free.md
        - pwn/linux/glibc-heap/implementation/tcache.md
        - pwn/linux/glibc-heap/implementation/malloc_state.md
        - pwn/linux/glibc-heap/implementation/misc.md
      - pwn/linux/glibc-heap/heapoverflow_basic.md
      - pwn/linux/glibc-heap/off_by_one.md
      - pwn/linux/glibc-heap/chunk_extend_overlapping.md
      - pwn/linux/glibc-heap/unlink.md
      - pwn/linux/glibc-heap/use_after_free.md
      - pwn/linux/glibc-heap/fastbin_attack.md
      - pwn/linux/glibc-heap/unsorted_bin_attack.md
      - pwn/linux/glibc-heap/large_bin_attack.md
      - pwn/linux/glibc-heap/tcache_attack.md
      - pwn/linux/glibc-heap/house_of_einherjar.md
      - pwn/linux/glibc-heap/house_of_force.md
      - pwn/linux/glibc-heap/house_of_lore.md
      - pwn/linux/glibc-heap/house_of_orange.md
      - pwn/linux/glibc-heap/house_of_rabbit.md
      - pwn/linux/glibc-heap/house_of_roman.md
      - pwn/linux/glibc-heap/house_of_pig.md
    - IO_FILE 利用:
      - pwn/linux/io_file/introduction.md
      - pwn/linux/io_file/fake-vtable-exploit.md
      - pwn/linux/io_file/fsop.md
      - pwn/linux/io_file/exploit-in-libc2.24.md
    - 条件竞争:
      - pwn/linux/race-condition/introduction.md
      - pwn/linux/race-condition/problem.md
    - 整数溢出:
      - pwn/linux/integeroverflow/intof.md
    - 沙箱逃逸:
      - pwn/linux/sandbox/python-sandbox-escape.md
      - pwn/linux/sandbox/c-sandbox-escape.md
    - kernel:
      - pwn/linux/kernel/environment.md
      - pwn/linux/kernel/basic_knowledge.md
      - pwn/linux/kernel/kernel_uaf.md
      - pwn/linux/kernel/kernel_rop.md
      - pwn/linux/kernel/ret2usr.md
      - pwn/linux/kernel/bypass_smep.md
      - pwn/linux/kernel/double-fetch.md
    - arm-pwn:
      - pwn/linux/arm/environment.md
      - pwn/linux/arm/arm_rop.md
    - mips-pwn:
      - pwn/linux/mips/mips_rop.md
    - Summary:
      - pwn/linux/summary/get-address.md
      - pwn/linux/summary/hijack-control-flow.md
      - pwn/linux/summary/get-shell.md
  - Windows Pwn:
    - pwn/windows/readme.md
    - 栈溢出:
      - pwn/windows/stackoverflow/stack-introduce.md
      - pwn/windows/stackoverflow/stackoverflow-basic.md
      - pwn/windows/stackoverflow/shellcode-in-stack.md
- Android:
  - android/basic_develop/basic_develop.md
  - Android 运行机制简述:
    - android/basic_operating_mechanism/readme.md
    - Android 中 Java 层的运行机制:
      - android/basic_operating_mechanism/java_layer/readme.md
      - android/basic_operating_mechanism/java_layer/smali/smali.md
      - Dex && ODEX:
        - android/basic_operating_mechanism/java_layer/dex/dex.md
        - android/basic_operating_mechanism/java_layer/dex/odex.md
    - Android Native 层介绍:
      - android/basic_operating_mechanism/native_layer/so.md
  - Android 逆向基本介绍:
    - android/basic_reverse/overview.md
    - android/basic_reverse/android_code_location.md
    - Android 简单静态分析:
      - android/basic_reverse/static/java-example.md
      - android/basic_reverse/static/so-example.md
      - android/basic_reverse/static/complex-example.md
    - Android 简单动态分析:
      - android/basic_reverse/dynamic/dynamic_debug.md
      - android/basic_reverse/dynamic/ida_native_debug.md
- ICS:
  - ics/ctfs.md
  - ics/discover.md
  - ics/exploit.md
  - ics/learn.md
- BlockChain:
  - blockchain/introduction.md
  - Ethereum Security:
    - blockchain/ethereum/introduction.md
    - blockchain/ethereum/basics.md
    - blockchain/ethereum/selector-encoding.md
    - blockchain/ethereum/storage.md
    - blockchain/ethereum/opcodes.md
    - Known Attacks:
      - blockchain/ethereum/attacks/introduction.md
      - blockchain/ethereum/attacks/re-entrancy.md
      - blockchain/ethereum/attacks/overflow-underflow.md
      - blockchain/ethereum/attacks/randomness.md
      - blockchain/ethereum/attacks/airdrop-hunting.md
      - blockchain/ethereum/attacks/shortaddress.md
      - blockchain/ethereum/attacks/delegatecall.md
      - blockchain/ethereum/attacks/uninitialized-storage-pointer.md
      - blockchain/ethereum/attacks/arbitrarywrite.md
      - blockchain/ethereum/attacks/create2.md
      - blockchain/ethereum/attacks/jump-oriented-programming.md
    - blockchain/ethereum/reverse.md
    - blockchain/ethereum/challenges.md
    - blockchain/ethereum/resources.md
  - Public Blockchain Security:
    - blockchain/publicblockchain/introduction.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  alternate:
  - link: /
    name: zh - 汉语
  - link: /en/
    name: en - English
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
